version: '3.9'

services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: backend
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
      # postgresql://webstore_user:12345@127.0.0.1:5432/webstore_database
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
volumes:
  postgres_data:
